---
version: "3.8"
services:
  app:
    image: app
    build: ./src
    env_file:
      - .env
    volumes:
      - ./src/app/data:/src/app/data
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
